// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeCWVH4pRht3J_ORb9iEPqyXkcwGp4iXw',
    appId: '1:243981485048:web:fa66f30e36d411f8f48c0d',
    messagingSenderId: '243981485048',
    projectId: 'mazraa-fe2b0',
    authDomain: 'mazraa-fe2b0.firebaseapp.com',
    storageBucket: 'mazraa-fe2b0.appspot.com',
    measurementId: 'G-PCXYXXYLZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIiJXmgPVMFHTbT8_mZvm6o_yjqt6ltrc',
    appId: '1:243981485048:android:2fc1c1e59b336b53f48c0d',
    messagingSenderId: '243981485048',
    projectId: 'mazraa-fe2b0',
    storageBucket: 'mazraa-fe2b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMlwFjwyfn0ExqzKGfo4HxBpCdS5fy9x8',
    appId: '1:243981485048:ios:30d6c6af8926db20f48c0d',
    messagingSenderId: '243981485048',
    projectId: 'mazraa-fe2b0',
    storageBucket: 'mazraa-fe2b0.appspot.com',
    iosBundleId: 'com.example.mazraamarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMlwFjwyfn0ExqzKGfo4HxBpCdS5fy9x8',
    appId: '1:243981485048:ios:4b6ece8c37cbb55ff48c0d',
    messagingSenderId: '243981485048',
    projectId: 'mazraa-fe2b0',
    storageBucket: 'mazraa-fe2b0.appspot.com',
    iosBundleId: 'com.example.mazraamarket.RunnerTests',
  );
}
